import {
  BarChart3,
  Bot,
  CalendarClock,
  CalendarRange,
  Palette,
  CheckSquare,
  CircleUserRound,
  FileText,
  FileBarChart,
  FolderKanban,
  Home,
  IdCard,
  MailCheck,
  MonitorPlay,
  MessageSquare,
  MessageSquareText,
  Phone,
  Settings,
  Share2,
  TrendingUp,
  UsersRound,
  UserCircle,
  Waves,
} from "lucide-react";
import { PERMISSIONS } from "@/lib/rbac/permissions";

export const dashboardNavItems = [
  { href: "/dashboard", label: "Dashboard", icon: Home },
  { href: "/dashboard/participants", label: "Participants", icon: UsersRound },
  { href: "/dashboard/contacts", label: "Contacts", icon: UserCircle },
  { href: "/dashboard/waves", label: "Waves", icon: Waves },
  { href: "/dashboard/check-in-results", label: "Check-In Results", icon: CheckSquare },
  { href: "/dashboard/surveys", label: "Surveys", icon: MessageSquareText },
  { href: "/dashboard/pastor-elder-review", label: "Pastor/Elder Review", icon: CircleUserRound },
  { href: "/dashboard/inner-circle", label: "Inner Circle", icon: CalendarRange },
  { href: "/dashboard/blog-posts", label: "Blog Posts", icon: FileText, permission: PERMISSIONS.REVIEW_CONTENT },
  { href: "/dashboard/impact-score", label: "Impact Score", icon: TrendingUp, permission: PERMISSIONS.REVIEW_CONTENT },
  { href: "/dashboard/emails", label: "Emails", icon: MailCheck },
  { href: "/dashboard/sms", label: "SMS", icon: MessageSquare },
  { href: "/dashboard/dialer", label: "Dialer", icon: Phone },
  { href: "/dashboard/social-media", label: "Social Media", icon: Share2 },
  { href: "/dashboard/business-cards", label: "Business Cards", icon: IdCard },
  { href: "/dashboard/project-manager", label: "Project Manager", icon: FolderKanban },
  { href: "/dashboard/bookings", label: "Bookings & Events", icon: CalendarClock },
  { href: "/dashboard/ai-agent", label: "AI Agent", icon: Bot, permission: PERMISSIONS.MANAGE_SETTINGS },
  { href: "/dashboard/media-studio", label: "Media Studio", icon: MonitorPlay, permission: PERMISSIONS.MANAGE_SETTINGS },
  { href: "/dashboard/assets", label: "Assets", icon: Palette, permission: PERMISSIONS.MANAGE_SETTINGS },
  { href: "/dashboard/reports", label: "Reports", icon: FileBarChart },
  { href: "/dashboard/settings", label: "Settings", icon: Settings, permission: PERMISSIONS.MANAGE_SETTINGS },
  { href: "/dashboard/user-management", label: "User Management", icon: BarChart3, permission: PERMISSIONS.MANAGE_USERS },
] as const;
