insert into public.tags (name, category) values
  ('Created for More Pilot', 'pilot'),
  ('Wave 0', 'wave'),
  ('Wave 1', 'wave'),
  ('Wave 2', 'wave'),
  ('Wave 3', 'wave'),
  ('Pastor/Elder Review', 'review'),
  ('Church Leader', 'relationship'),
  ('Check-In Started', 'check_in'),
  ('Check-In Completed', 'check_in'),
  ('7-Day Journey Started', 'journey'),
  ('7-Day Journey Completed', 'journey'),
  ('Survey Sent', 'survey'),
  ('Survey Completed', 'survey'),
  ('Inner Circle Invited', 'inner_circle'),
  ('Inner Circle Accepted', 'inner_circle'),
  ('Story Permission Granted', 'permission'),
  ('Interview Candidate', 'follow_up'),
  ('Church Pilot Interest', 'interest'),
  ('Small Group Interest', 'interest'),
  ('Bible Plan Interest', 'interest'),
  ('Workbook Interest', 'interest'),
  ('Speaking Interest', 'interest'),
  ('Referral / Shared With Others', 'referral'),
  ('Lowest: Purpose', 'lowest_area'),
  ('Lowest: Family', 'lowest_area'),
  ('Lowest: Fitness/Energy', 'lowest_area'),
  ('Lowest: Fun/Joy', 'lowest_area'),
  ('Lowest: Finances', 'lowest_area')
on conflict (name) do nothing;
