export const WAVE_SOURCE_VALUES = [
  "wave_0",
  "wave_1",
  "wave_2",
  "wave_3",
  "pastor_elder",
  "inner_circle",
  "direct_text",
  "direct_email",
  "referral",
  "manual_admin",
] as const;

export type WaveSource = (typeof WAVE_SOURCE_VALUES)[number];

export const PARTICIPANT_TYPES = {
  GENERAL: "general_participant",
  PASTOR_ELDER: "pastor_elder_church_leader",
} as const;

// The Created for More Check-In — the full Stewardship Blueprint: 7 layers,
// 4 statements each, rated 1-5 → a Blueprint Alignment Score out of 140.
export const CHECK_IN_SECTIONS = [
  {
    key: "bedrock",
    title: "Bedrock — Faith & Identity",
    lowestTag: "Lowest: Bedrock",
    coreQuestion: "Is my identity rooted in something deeper than performance and pressure?",
    questions: [
      "I know who I am beneath my roles, titles, and achievements.",
      "My daily choices flow from a settled identity, not from proving myself.",
      "I return to my faith as a source of stability, not just a Sunday habit.",
      "I can name the truth I stand on when life feels uncertain.",
    ],
  },
  {
    key: "foundation",
    title: "Foundation — Mission, Values & Purpose",
    lowestTag: "Lowest: Foundation",
    coreQuestion: "Am I living with clarity about what kind of life I am building?",
    questions: [
      "I have clarity about what matters most in this season.",
      "My calendar reflects my stated priorities.",
      "I could state my mission and values in a sentence if asked.",
      "I am building my life around purpose, not just pressure or expectation.",
    ],
  },
  {
    key: "pillars",
    title: "The Four Pillars — Family, Fitness, Fun & Finances",
    lowestTag: "Lowest: Four Pillars",
    coreQuestion: "Are the areas I stand on every day actually able to hold weight?",
    questions: [
      "The people I love are receiving my presence, not just my provision. (Family)",
      "My sleep, movement, and health support the life I want to build. (Fitness)",
      "I make room for joy, rest, and meaningful experiences — not just obligation. (Fun)",
      "My finances serve my purpose and values, not fear or comparison. (Finances)",
    ],
  },
  {
    key: "guardrails",
    title: "Guardrails — Boundaries That Protect What Matters",
    lowestTag: "Lowest: Guardrails",
    coreQuestion: "Do I have boundaries in place before I need them — not just after damage is done?",
    questions: [
      "I have clear boundaries around my time, attention, and commitments.",
      "I have limits in place that protect my integrity under pressure.",
      "I say no to good things that would crowd out my best things.",
      "Someone else knows my guardrails and helps me keep them.",
    ],
  },
  {
    key: "habits",
    title: "Keystone Habits — Small Rhythms That Strengthen the Structure",
    lowestTag: "Lowest: Keystone Habits",
    coreQuestion: "Do my daily habits move me toward the life I say I want?",
    questions: [
      "I have identified one or two habits that, if kept, would change everything else.",
      "My mornings or evenings have a rhythm that supports who I am trying to become.",
      "When a keystone habit slips, I notice quickly and recover instead of spiraling.",
      "My habits are shaping my identity, not just filling my to-do list.",
    ],
  },
  {
    key: "energy",
    title: "Energy — The Resource Beneath Every Other Resource",
    lowestTag: "Lowest: Energy",
    coreQuestion: "Am I stewarding the energy beneath everything I do?",
    questions: [
      "I know where my physical, emotional, mental, and spiritual energy actually goes.",
      "I have rhythms of renewal built in before I hit empty, not just after.",
      "I recognize the difference between being busy and being depleted.",
      "I am living on today's connection with God, not yesterday's.",
    ],
  },
  {
    key: "legacy",
    title: "Legacy — What Your Life Multiplies",
    lowestTag: "Lowest: Legacy",
    coreQuestion: "What is my life producing beyond me?",
    questions: [
      "I am intentionally shaping what the next generation sees in me.",
      "My time, money, and influence are aligned with what I want to leave behind.",
      "I have had a real conversation about legacy with someone I love.",
      "I am building something today that will outlast me.",
    ],
  },
] as const;

export type CheckInSectionKey = (typeof CHECK_IN_SECTIONS)[number]["key"];

export const REFLECTION_PROMPTS = [
  "In this season, I sense I need to pay attention to:",
  "This week, I will take this small action:",
  "One person I may need to talk with about this is:",
  "One rhythm, habit, or calendar adjustment that could help is:",
] as const;

export const DEFAULT_TAGS = [
  "Created for More Pilot",
  "Wave 0",
  "Wave 1",
  "Wave 2",
  "Wave 3",
  "Pastor/Elder Review",
  "Church Leader",
  "Check-In Started",
  "Check-In Completed",
  "7-Day Journey Started",
  "7-Day Journey Completed",
  "Survey Sent",
  "Survey Completed",
  "Inner Circle Invited",
  "Inner Circle Accepted",
  "Story Permission Granted",
  "Interview Candidate",
  "Church Pilot Interest",
  "Small Group Interest",
  "Bible Plan Interest",
  "Workbook Interest",
  "Speaking Interest",
  "Referral / Shared With Others",
  "Lowest: Bedrock",
  "Lowest: Foundation",
  "Lowest: Four Pillars",
  "Lowest: Guardrails",
  "Lowest: Keystone Habits",
  "Lowest: Energy",
  "Lowest: Legacy",
] as const;

export const SCORE_RANGE_LABELS = {
  aligned: "Aligned & Intentional",
  stretched: "Aware but Stretched",
  drifting: "Drifting in Key Layers",
  rebuild: "Time to Pause & Rebuild",
} as const;

export const GENERAL_SURVEY_FIELDS = [
  { name: "name", label: "Name", type: "text", required: true },
  { name: "email", label: "Email", type: "email", required: true },
  { name: "checkInScore", label: "What was your total Created for More Check-In score?", type: "number" },
  {
    name: "lowestArea",
    label: "Which area was your lowest score?",
    type: "select",
    options: [
      "Bedrock — Faith & Identity",
      "Foundation — Mission, Values & Purpose",
      "The Four Pillars — Family, Fitness, Fun & Finances",
      "Guardrails",
      "Keystone Habits",
      "Energy",
      "Legacy",
      "I am not sure / I do not remember",
    ],
  },
  {
    name: "resonantDay",
    label: "Which day of the 7-day journey resonated most with you?",
    type: "select",
    options: [
      "Day 1 — What Kind of Life Are You Actually Building?",
      "Day 2 — Faith at the Center",
      "Day 3 — Purpose, Scoreboards, and Drift",
      "Day 4 — Family and Relationships",
      "Day 5 — Fitness, Energy, and Capacity",
      "Day 6 — Fun, Joy, Money, and Meaningful Resources",
      "Day 7 — One Faithful Next Step",
    ],
  },
  { name: "whyResonated", label: "Why did that day resonate most?", type: "textarea" },
  { name: "stayedWithYou", label: "What phrase, question, or idea stayed with you the most?", type: "textarea" },
  { name: "sawDrift", label: "Did the 7-day journey help you see any area of drift or misalignment in your life?", type: "select", options: ["Yes, clearly", "Somewhat", "Not really", "I am still processing"] },
  { name: "clearerArea", label: "If yes, what area did it help you see more clearly?", type: "textarea" },
  { name: "tookAction", label: "Did you take any action during the 7 days?", type: "select", options: ["Yes", "Not yet, but I plan to", "No"] },
  { name: "actionTaken", label: "If yes, what action did you take?", type: "textarea" },
  { name: "conversation", label: "Did you have a conversation you may not have had otherwise?", type: "select", options: ["Yes", "Not yet, but I plan to", "No"] },
  { name: "newRhythm", label: "Did you identify or begin one new rhythm, habit, or calendar adjustment?", type: "select", options: ["Yes", "Not yet, but I plan to", "No"] },
  { name: "tone", label: "How would you describe the tone of the journey?", type: "select", options: ["Encouraging", "Convicting", "Both encouraging and convicting", "Too soft", "Too intense", "Unclear"] },
  { name: "faithContent", label: "How did the faith content feel to you?", type: "select", options: ["About right", "Too light", "Too heavy", "Clear and helpful", "Unclear", "Not applicable to me"] },
  { name: "mostHelpful", label: "What felt most helpful?", type: "textarea" },
  { name: "missing", label: "What felt missing, unclear, repetitive, or less helpful?", type: "textarea" },
  { name: "practicalEnough", label: "Did the journey feel practical enough to help someone take action?", type: "select", options: ["Yes", "Somewhat", "Not yet", "Unsure"] },
  { name: "moreUseful", label: "What would make this more useful or transformational?", type: "textarea" },
  { name: "whoNeedsThis", label: "Who do you think most needs this message right now?", type: "textarea" },
  { name: "recommend", label: "Would you recommend this to someone else?", type: "select", options: ["Yes", "Maybe", "Not yet"] },
  { name: "shareWith", label: "Who would you be most likely to share this with?", type: "select", options: ["Friend", "Spouse", "Family member", "Coworker", "Small group", "Church leader", "Client/customer", "Other"] },
  { name: "futureResource", label: "What future resource would be most helpful?", type: "checkbox", options: ["Bible plan", "Small-group study", "Workbook", "Video series", "Live workshop", "Church class", "Online community", "Book companion guide", "Family/couples guide", "Men’s group version", "Financial stewardship guide"] },
  { name: "innerCircle", label: "Would you be open to joining a smaller Inner Circle to continue helping shape the book and future resources?", type: "select", options: ["Yes", "Maybe", "No"] },
  { name: "followUp", label: "May Mike follow up with you about your feedback?", type: "select", options: ["Yes", "No"] },
  { name: "storyInterview", label: "May Mike contact you about a possible quote, story, or interview?", type: "select", options: ["Yes", "Maybe", "No"] },
  { name: "anonymousUse", label: "May your feedback be used anonymously to improve the book and future resources?", type: "select", options: ["Yes", "No"] },
  { name: "finalNeed", label: "Final question: What do you think people most need from this message right now?", type: "textarea" },
] as const;

export const PASTOR_ELDER_SURVEY_FIELDS = [
  { name: "name", label: "Name", type: "text", required: true },
  { name: "email", label: "Email", type: "email", required: true },
  { name: "churchOrganization", label: "Church / organization", type: "text" },
  { name: "role", label: "Role", type: "select", options: ["Senior pastor", "Executive pastor", "Teaching pastor", "Associate pastor", "Elder", "Ministry leader", "Small-group leader", "Other"] },
  { name: "biblicallyGrounded", label: "Did the 7-day journey feel biblically grounded?", type: "select", options: ["Yes", "Mostly", "Somewhat", "Not yet", "Unsure"] },
  { name: "theologyClarity", label: "Where, if anywhere, does the biblical or theological foundation need more clarity?", type: "textarea" },
  { name: "pastorallyHelpful", label: "Did the tone feel pastorally helpful?", type: "select", options: ["Yes", "Mostly", "Somewhat", "Not yet", "Unsure"] },
  { name: "convictingNotCondemning", label: "Did the content feel convicting without being condemning?", type: "select", options: ["Yes", "Mostly", "Somewhat", "Not yet", "Unsure"] },
  { name: "mostHelpful", label: "What part felt most pastorally helpful?", type: "textarea" },
  { name: "beCarefulWith", label: "What part would you want me to be careful with?", type: "textarea" },
  { name: "churchUse", label: "Could you see this serving people in a church setting?", type: "select", options: ["Yes", "Possibly", "Not yet", "Unsure"] },
  { name: "churchSetting", label: "Which church setting seems most natural?", type: "checkbox", options: ["Men’s group", "Couples group", "Small group", "Adult class", "Stewardship class", "Leadership cohort", "Marriage/family ministry", "Financial stewardship ministry", "Sermon series support", "Church-wide campaign", "Young adults", "Parents", "Business leaders", "Other"] },
  { name: "audience", label: "What audience in your church or ministry do you think most needs this?", type: "textarea" },
  { name: "concerns", label: "What concerns would you have before recommending this to a church group?", type: "textarea" },
  { name: "leaderNeeds", label: "What would need to be added for a small-group leader to use this well?", type: "textarea" },
  { name: "studyLength", label: "Would this work better as a 4-week, 6-week, or 7-week small-group study?", type: "select", options: ["4-week", "6-week", "7-week", "Unsure", "Other"] },
  { name: "topicsExpanded", label: "What topics should be expanded for church use?", type: "checkbox", options: ["Faith at the center", "Family and relationships", "Health and energy", "Joy, Sabbath, and meaningful experiences", "Financial stewardship", "Guardrails", "Habits", "Generosity and legacy", "Raising the next generation", "Purpose and calling", "Other"] },
  { name: "businessOrChurchFit", label: "Did anything feel too business-oriented, too financial, or not church-friendly enough?", type: "textarea" },
  { name: "spiritualWeight", label: "Did anything feel too light spiritually or too heavy spiritually?", type: "textarea" },
  { name: "scriptureTheme", label: "What Scripture, theological theme, or discipleship emphasis would you suggest strengthening?", type: "textarea" },
  { name: "followUpConversation", label: "Would you be open to a follow-up conversation with Michael?", type: "select", options: ["Yes", "Maybe", "No"] },
  { name: "futureReview", label: "Would you be open to reviewing future versions of a small-group study, Bible plan, or church resource?", type: "select", options: ["Yes", "Maybe", "No"] },
  { name: "anonymousUse", label: "May Michael use your feedback anonymously to improve the book and future resources?", type: "select", options: ["Yes", "No"] },
  { name: "storyInterview", label: "May Michael contact you about a possible quote, endorsement, story, or interview in the future?", type: "select", options: ["Yes", "Maybe", "No"] },
  { name: "finalNeed", label: "Final question: What do you think people most need from this message right now?", type: "textarea" },
] as const;
